// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACR4uS6J0Xf41poK_yMszt8V6ycbIMD04',
    appId: '1:380222998663:web:0134957ee90508fbbfd022',
    messagingSenderId: '380222998663',
    projectId: 'food-delivery-app-c9657',
    authDomain: 'food-delivery-app-c9657.firebaseapp.com',
    storageBucket: 'food-delivery-app-c9657.firebasestorage.app',
    measurementId: 'G-W15MYMV50N',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACR4uS6J0Xf41poK_yMszt8V6ycbIMD04',
    appId: '1:380222998663:web:f2dcf848bf5b2605bfd022',
    messagingSenderId: '380222998663',
    projectId: 'food-delivery-app-c9657',
    authDomain: 'food-delivery-app-c9657.firebaseapp.com',
    storageBucket: 'food-delivery-app-c9657.firebasestorage.app',
    measurementId: 'G-QZFXBYGQS3',
  );
}
